export enum ErrorCodes {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  JWT_EXPIRED_ERROR = 'JWT_EXPIRED_ERROR',
  ISSUER_AUTH_NOT_PROVIDED = 'ISSUER_AUTH_NOT_PROVIDED',
  INVALID_OTP_CODE = 'INVALID_OTP_CODE',
  CLOUD_WALLET_NOT_AUTHENTICATED = 'CLOUD_WALLET_NOT_AUTHENTICATED',
  HTTP_METHOD_NOT_ALLOWED = 'HTTP_METHOD_NOT_ALLOWED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SCAN_ERROR = 'SCAN_ERROR',
}
